name: RandomItemChallenge
author: Lanfix
version: 1.1.5
main: fr.lanfix.randomitemchallenge.Main
api-version: 1.19
commands:
  randomitemchallenge:
    description: Start or stop the Random Item Challenge
    permission: randomitemchallenge.start
    usage: /randomitemchallenge