name: RandomItemChallenge
author: Lanfix
version: '${project.version}'
main: fr.lanfix.randomitemchallenge.RandomItemChallenge
api-version: 1.21
commands:
  randomitemchallenge:
    description: Start or stop the Random Item Challenge
    permission: randomitemchallenge.start
    usage: /randomitemchallenge
softdepend:
  - Chunky
  - PlaceholderAPI