name: RandomItemChallenge
author: Lanfix
version: '${project.version}'
main: fr.lanfix.randomitemchallenge.RandomItemChallenge
api-version: 1.21.6
commands:
  randomitemchallenge:
    aliases:
      - ric
    description: Start or stop the Random Item Challenge
    permission: randomitemchallenge.admin
    usage: /randomitemchallenge <start|stop|scenario|reload>
softdepend:
  - Chunky
  - PlaceholderAPI